from lib import Module

m = Module(
    key="sales", title="Sales & Cashier API v1", codes="BH, TG", owner="BE-2",
    sources="01 UC66, UC67, UC70–UC72; 02 BR-BH-01…06, BR-TG-01…05, BR-TN-01, 08, BR-KB-03, 04, BR-LT-09, BR-SP-01, BR-QT-15; 03 #5 Order, #8 Ca thu ngân; 04 §8; 05 §8 (orders, order_lines, payments, cashier_shifts)",
    intro="Order tại quầy (VISIT / RETAIL / BOARDING), dòng Order, chốt / hủy, thu tiền (thu gộp), ca thu ngân, đối soát.",
    frozen=[
        "UC61–UC65 (giỏ hàng, đơn online, thanh toán cổng) và UC68–UC69 (trả hàng) là tầng 3.",
        "Order VISIT được mở / chốt / hủy theo Visit (Order#1, #4, #6) qua `VisitOrderApi`; Order BOARDING sinh khi bắt đầu trả thú / thú mất (Order#3) qua `BoardingOrderApi`. Không có endpoint tạo Order nguồn VISIT hay BOARDING.",
        "Dòng DRUG sinh từ kê đơn (`/visits/{visitId}/prescriptions`), dòng VACCINE từ ghi mũi tiêm, dòng BOARDING từ trả thú. Ở đây chỉ thêm dòng SERVICE và GOODS.",
        "ST06 trừ kho chạy trong `POST /payments`; ST13 (tự chốt ca, cảnh báo Order PENDING quá hạn) là tác vụ hệ thống.",
    ],
    tags={
        "Orders": "Order và dòng Order (UC66, UC67)",
        "Payments": "Thu tiền tại quầy, thu gộp (UC70)",
        "Cashier shifts": "Mở / chốt ca, đối soát (UC71, UC72)",
    },
    security=[
        "Nhân viên chỉ thao tác Order, phiếu thu, ca của chi nhánh mình.",
        "Quyền thêm / xóa dòng theo BR-BH-02: VET thêm dịch vụ cho Visit mình phụ trách, CARETAKER thêm dịch vụ thẩm mỹ, lễ tân thêm hàng bán lẻ; dòng chỉ xóa bởi `ownerAccountId`; khi PENDING chỉ lễ tân thêm / xóa dòng bán lẻ. Request ngoài quyền trả 403.",
        "Thu tiền là một transaction: khóa các Order, kiểm PENDING và cùng khách / chi nhánh, khóa lô, kiểm tồn, ghi phiếu thu, chuyển PAID, trừ kho FEFO, ghi audit (05 `payments`, BR-BH-04, BR-TG-04). Hai quầy thu cùng lúc không làm tồn âm.",
        "Hủy Order từ PENDING, hủy phiên trả thú, chuyển thuốc sang mua ngoài lúc thu, đối soát ca đều bắt buộc lý do / ghi chú và ghi audit (BR-QT-15).",
        "Hàng và thú chỉ giao khi Order PAID; response có `deliveryAllowed` để FE hiển thị 'Chưa thanh toán – chưa giao hàng' (BR-BH-06).",
    ],
    assumptions=[
        ("A1", "Order bán lẻ bắt buộc gắn hồ sơ khách", "05 `orders.customer_id` NOT NULL; khách lạ thì lễ tân tạo hồ sơ tại quầy trước"),
        ("A2", "Có endpoint xem trước khi thu (`/payments/preview`) trả tổng tiền và danh sách dòng thiếu tồn", "BR-BH-04: từ chối thu và chỉ rõ dòng thiếu; envelope lỗi không chứa danh sách"),
        ("A3", "Ba thao tác hủy là ba endpoint riêng theo người kích hoạt và trạng thái (Order#7, #9, #10)", "Mỗi chuyển có người kích hoạt và điều kiện khác nhau trong 03 #5"),
        ("A4", "`countedCash` chỉ đếm tiền mặt; chuyển khoản lễ tân xác nhận từng phiếu thu nên không đếm lại", "BR-TG-02; 05 `cashier_shifts` chỉ có `counted_cash`"),
        ("A5", "VET / CARETAKER đổi dịch vụ của dòng tự sinh bằng PATCH `serviceId`, giá snapshot lại tại thời điểm đổi", "BR-TN-01 cho phép đổi; BR-BH-03 snapshot khi thêm dòng"),
    ],
    questions=[],
)

m.param("OrderId", "orderId", "path", "int64")
m.param("LineId", "lineId", "path", "int64")
m.param("PaymentId", "paymentId", "path", "int64")
m.param("ShiftId", "shiftId", "path", "int64")
m.param("CustomerId", "customerId", "path", "int64")

m.schema("OrderSource", None, enum=["VISIT", "RETAIL", "BOARDING"])
m.schema("OrderStatus", None, enum=["OPEN", "PENDING", "PAID", "CANCELLED"], desc="03 #5")
m.schema("OrderLine", {
    "lineId": "int64", "lineType": "enum:SERVICE,GOODS,DRUG,VACCINE,BOARDING", "serviceId": "int64?",
    "productId": "int64?", "description": "string|Tên lúc thêm dòng", "quantity": "int|Với BOARDING là số đêm",
    "unitPrice": "money|Snapshot (BR-BH-03)", "lineTotal": "money", "isAutoGenerated": "bool",
    "addedBy": "int64", "ownerAccountId": "int64|Người có quyền xóa (BR-BH-02, BR-TN-08)",
    "canEdit": "bool|Theo người đang xem", "canDelete": "bool|Theo người đang xem; dòng VACCINE luôn false",
})
m.schema("Order", {
    "orderId": "int64", "code": "string", "source": "ref:OrderSource", "status": "ref:OrderStatus",
    "customerId": "int64", "customerName": "string", "branchId": "int64", "visitId": "int64?",
    "boardingBookingId": "int64?", "totalAmount": "money", "lines": "array:ref:OrderLine",
    "createdAt": "datetime", "pendingAt": "datetime?", "paidAt": "datetime?", "paymentId": "int64?",
    "cancelType": "enum:VISIT_CANCELLED,RETAIL_UNCLOSED,CHECKOUT_ABORTED,UNPAID?", "cancelReason": "string?",
    "cancelledAt": "datetime?", "deliveryAllowed": "bool|true chỉ khi PAID (BR-BH-06)",
})
m.schema("OrderSummary", {
    "orderId": "int64", "code": "string", "source": "ref:OrderSource", "status": "ref:OrderStatus",
    "customerId": "int64", "customerName": "string", "branchId": "int64", "totalAmount": "money",
    "createdAt": "datetime", "pendingAt": "datetime?", "paidAt": "datetime?",
})
m.schema("CreateRetailOrderRequest", {"customerId": "int64|A1"})
m.schema("AddOrderLineRequest", {
    "lineType": "enum:SERVICE,GOODS", "serviceId": "int64?|SERVICE: nhóm khớp vai trò (VET: MEDICAL, CARETAKER: GROOMING)",
    "productId": "int64?|GOODS: không phải thuốc kê đơn (BR-SP-01)", "quantity": "int|> 0",
})
m.schema("StockWarning", {"productId": "int64", "requested": "int", "available": "int"})
m.schema("AddOrderLineResult", {
    "order": "ref:Order", "lineId": "int64",
    "stockWarning": "ref:StockWarning",
}, required=["order", "lineId"], desc="stockWarning có khi hàng bán lẻ thiếu tồn khả dụng — cảnh báo, không chặn (BR-BH-04)")
m.schema("UpdateOrderLineRequest", {
    "quantity": "int?|Giảm dòng bán lẻ (BR-BH-04)",
    "serviceId": "int64?|Người được gán lượt đổi dịch vụ của dòng tự sinh (BR-TN-01, A5)",
}, required=[])
m.schema("ReasonRequest", {"reason": "string:300"})
m.schema("ShortageLine", {
    "orderId": "int64", "lineId": "int64", "lineType": "enum:GOODS,DRUG", "productId": "int64",
    "productName": "string", "requested": "int", "available": "int",
})
m.schema("PaymentPreviewRequest", {"orderIds": "array:int64|Các Order PENDING cùng khách, cùng chi nhánh (BR-TG-03)"})
m.schema("PaymentPreview", {
    "customerId": "int64", "branchId": "int64", "totalAmount": "money",
    "shortages": "array:ref:ShortageLine|Rỗng mới thu được; bỏ qua dòng VACCINE (BR-BH-04)",
})
m.schema("CreatePaymentRequest", {
    "orderIds": "array:int64", "method": "enum:CASH,TRANSFER",
    "amount": "money|Phải bằng tổng các Order (BR-TG-02)",
})
m.schema("Payment", {
    "paymentId": "int64", "code": "string|Số phiếu thu", "branchId": "int64", "customerId": "int64",
    "cashierShiftId": "int64", "method": "enum:CASH,TRANSFER", "amount": "money", "receivedBy": "int64",
    "paidAt": "datetime", "orders": "array:ref:OrderSummary",
})
m.schema("CashierShift", {
    "shiftId": "int64", "branchId": "int64", "cashierId": "int64", "cashierName": "string",
    "isAfterHours": "bool|Ca ngoài giờ thu tiền cấp cứu (BR-CN-05)", "businessDate": "date",
    "status": "enum:OPEN,CLOSED,RECONCILED", "openedAt": "datetime", "closedAt": "datetime?",
    "autoClosed": "bool|ST13", "expectedCash": "money?", "expectedTransfer": "money?", "countedCash": "money?",
    "difference": "int64?|countedCash − expectedCash (VND), có thể âm", "reconcileNote": "string?",
    "reconciledBy": "int64?", "reconciledAt": "datetime?", "paymentCount": "int",
})
m.schema("OpenShiftRequest", {"afterHours": "bool|false = ca thường, true = ca ngoài giờ (BR-TG-05)"})
m.schema("CurrentShift", {"open": "bool", "shift": "ref:CashierShift"}, required=["open"])
m.schema("CloseShiftRequest", {"countedCash": "money|Tiền mặt thực đếm (A4)"})
m.schema("ReconcileShiftRequest", {
    "countedCash": "money?|Bắt buộc với ca tự chốt (BR-TG-05)", "note": "string|Ghi chú chênh lệch",
})

ORDER_SCOPE = "Nhân viên chi nhánh của Order"
m.op("post", "/orders", "createRetailOrder", "Tạo Order bán lẻ", "Orders", "UC66", "BR-BH-01", "A06", "Lễ tân",
     "— → OPEN, RETAIL (Order#2)", body="CreateRetailOrderRequest", resp="Order", status=201,
     errors=(400, 401, 403, 404))
m.op("get", "/orders", "listOrders", "Danh sách Order", "Orders", "UC66, UC70, ST13", "BR-BH-05",
     "A05, A06, A07, A08", ORDER_SCOPE, resp="OrderSummary", page=True, errors=(400, 401, 403),
     query=["status=enum:OPEN,PENDING,PAID,CANCELLED", "source=enum:VISIT,RETAIL,BOARDING", "customerId=int64",
            "visitId=int64", "boardingBookingId=int64", "date=date",
            "pendingOverdue=bool|PENDING quá 1 ngày [CFG] — danh sách ST13 cho quản lý (BR-BH-05)", "page", "size"])
m.op("get", "/orders/{orderId}", "getOrder", "Chi tiết Order", "Orders", "UC66, UC67, UC70", "BR-BH-02, 06",
     "A05, A06, A07, A08", ORDER_SCOPE, resp="Order", path_params=["OrderId"], errors=(401, 403, 404))
m.op("post", "/orders/{orderId}/lines", "addOrderLine", "Thêm dịch vụ / hàng vào Order", "Orders", "UC66, UC67",
     "BR-BH-02, 03, 04, BR-SP-01", "A06, A07, A08",
     "Lễ tân: GOODS; VET: SERVICE nhóm MEDICAL của Visit mình; CARETAKER: SERVICE nhóm GROOMING của Visit mình",
     body="AddOrderLineRequest", resp="AddOrderLineResult", status=201, path_params=["OrderId"],
     errors=(400, 401, 403, 404, 409),
     err_desc={400: "`BR-SP-01` thuốc kê đơn (dùng kê đơn) · sản phẩm / dịch vụ ngừng kinh doanh",
               403: "`BR-BH-02` vai trò không được thêm loại dòng này",
               409: "Order không OPEN (khi PENDING chỉ lễ tân thêm GOODS) / đã PAID, CANCELLED"},
     notes="Giá snapshot lúc thêm. Thiếu tồn bán lẻ: cảnh báo, không chặn.")
m.op("patch", "/orders/{orderId}/lines/{lineId}", "updateOrderLine", "Sửa dòng (giảm số lượng / đổi dịch vụ tự sinh)",
     "Orders", "UC66, UC67", "BR-BH-02, 03, 04, BR-TN-01", "A06, A07, A08", "Chủ dòng (ownerAccountId)",
     body="UpdateOrderLineRequest", resp="Order", path_params=["OrderId", "LineId"], errors=(400, 401, 403, 404, 409),
     err_desc={403: "`BR-BH-02` không phải chủ dòng, hoặc dòng dịch vụ / thuốc đã khóa khi PENDING",
               409: "Order đã PAID / CANCELLED"})
m.op("delete", "/orders/{orderId}/lines/{lineId}", "deleteOrderLine", "Xóa dòng", "Orders", "UC66, UC67",
     "BR-BH-02, BR-KB-04", "A06, A07, A08", "Chủ dòng (ownerAccountId)", resp="Order", path_params=["OrderId", "LineId"],
     errors=(400, 401, 403, 404, 409),
     err_desc={400: "`BR-BH-02` dòng VACCINE không xóa trực tiếp (xóa mũi tiêm) · dòng DRUG xóa qua đơn thuốc",
               403: "`BR-BH-02` không phải chủ dòng", 409: "Order đã PAID / CANCELLED"})
m.op("post", "/orders/{orderId}/close", "closeRetailOrder", "Chốt Order bán lẻ", "Orders", "UC66", "BR-BH-01", "A06",
     "Lễ tân", "OPEN → PENDING, RETAIL (Order#5)", resp="Order", path_params=["OrderId"], errors=(400, 401, 403, 404, 409),
     err_desc={400: "`BR-BH-01` Order chưa có dòng nào", 409: "Không phải Order RETAIL OPEN"})
m.op("post", "/orders/{orderId}/cancel", "cancelRetailOrder", "Hủy Order bán lẻ chưa chốt", "Orders", "UC66",
     "BR-BH-01", "A06", "Lễ tân", "OPEN → CANCELLED, RETAIL (Order#7)", resp="Order", path_params=["OrderId"],
     errors=(401, 403, 404, 409), err_desc={409: "Không phải Order RETAIL OPEN"})
m.op("post", "/orders/{orderId}/abort-checkout", "abortBoardingCheckout", "Hủy phiên trả thú (khách không thanh toán)",
     "Orders", "UC59", "BR-LT-09, BR-QT-15", "A06", "Lễ tân", "PENDING → CANCELLED, BOARDING (Order#9)",
     body="ReasonRequest", resp="Order", path_params=["OrderId"], errors=(400, 401, 403, 404, 409),
     err_desc={400: "`BR-LT-09` thiếu lý do · thú không còn trong chuồng (dùng cancel-unpaid)",
               409: "Không phải Order BOARDING PENDING"},
     notes="cancelType = CHECKOUT_ABORTED, không tính thất thu. Đặt chỗ giữ trạng thái, tiếp tục tính đêm. Ghi audit.")
m.op("post", "/orders/{orderId}/cancel-unpaid", "cancelUnpaidOrder", "Hủy Order khách không thanh toán", "Orders",
     "UC66", "BR-BH-05, BR-BC-02, BR-QT-15", "A05", "Chỉ BRANCH_MANAGER chi nhánh", "PENDING → CANCELLED (Order#10)",
     body="ReasonRequest", resp="Order", path_params=["OrderId"], errors=(400, 401, 403, 404, 409),
     err_desc={400: "`BR-BH-05` thiếu lý do · Order BOARDING khi thú còn trong chuồng (xử lý theo BR-LT-09)",
               409: "Order không PENDING"},
     notes="cancelType = UNPAID (thất thu). Không đổi kho, bệnh án, lịch hẹn, lưu trú. Ghi audit.")
m.op("post", "/orders/{orderId}/lines/{lineId}/move-to-external-purchase", "moveDrugLineToExternalPurchase",
     "Chuyển dòng thuốc kê đơn sang mua ngoài khi thiếu tồn lúc thu", "Orders", "UC70", "BR-BH-04, BR-KB-03, BR-QT-15",
     "A06", "Lễ tân", resp="Order", path_params=["OrderId", "LineId"], errors=(400, 401, 403, 404, 409),
     err_desc={400: "Dòng không phải DRUG hoặc tồn vẫn đủ", 409: "Order không PENDING"},
     notes="Dòng bị xóa khỏi Order, vẫn in trên đơn thuốc (external_reason = OUT_OF_STOCK_AT_PAYMENT). Ghi audit.")

m.op("get", "/customers/{customerId}/payable-orders", "listPayableOrders", "Order PENDING của khách tại chi nhánh",
     "Payments", "UC70", "BR-TG-01, 03", "A06", "Lễ tân chi nhánh", resp="array:OrderSummary",
     path_params=["CustomerId"], errors=(401, 403, 404), notes="Dùng để chọn Order thu gộp.")
m.op("post", "/payments/preview", "previewPayment", "Xem trước khi thu (tổng tiền, dòng thiếu tồn)", "Payments",
     "UC70", "BR-TG-02, 03, BR-BH-04", "A06", "Lễ tân chi nhánh", body="PaymentPreviewRequest", resp="PaymentPreview",
     errors=(400, 401, 403, 404),
     err_desc={400: "`BR-TG-03` Order khác khách / khác chi nhánh · `BR-TG-01` có Order không PENDING"},
     notes="Không ghi gì (A2).")
m.op("post", "/payments", "collectPayment", "Thu tiền", "Payments", "UC70, ST06", "BR-TG-01…04, BR-BH-04, 06, BR-KO-05",
     "A06", "Lễ tân có ca OPEN của chính mình", "PENDING → PAID (Order#8) cho mọi Order trong phiếu",
     body="CreatePaymentRequest", resp="Payment", status=201, errors=(400, 401, 403, 404, 409),
     err_desc={400: "`BR-TG-01` chưa mở ca · `BR-TG-02` số tiền khác tổng · `BR-TG-03` Order khác khách / chi nhánh · `BR-BH-04` thiếu tồn (gọi preview để xem dòng thiếu)",
               409: "Có Order không còn PENDING · xung đột đồng thời"},
     notes="Trừ kho FEFO cùng transaction; ghi vào ca; ghi audit.")
m.op("get", "/payments/{paymentId}", "getPayment", "Chi tiết phiếu thu", "Payments", "UC70", "—", "A05, A06",
     "Nhân viên chi nhánh", resp="Payment", path_params=["PaymentId"], errors=(401, 403, 404))

m.op("post", "/cashier-shifts", "openCashierShift", "Mở ca thu ngân", "Cashier shifts", "UC71",
     "BR-TG-01, 05, BR-CN-05", "A06", "Lễ tân", "— → OPEN (Ca thu ngân#1 ca thường / #2 ca ngoài giờ)",
     body="OpenShiftRequest", resp="CashierShift", status=201, errors=(400, 401, 403, 409),
     err_desc={400: "`BR-TG-05` ca thường ngoài giờ mở cửa / ngày nghỉ; ca ngoài giờ trong giờ mở cửa · `BR-CN-05` chi nhánh không có cờ cấp cứu ngoài giờ",
               409: "Đã có ca OPEN của mình"})
m.op("get", "/me/cashier-shift", "getMyCurrentShift", "Ca đang mở của tôi", "Cashier shifts", "UC70, UC71",
     "BR-TG-01", "A06", "Lễ tân", resp="CurrentShift", errors=(401, 403))
m.op("post", "/cashier-shifts/{shiftId}/close", "closeCashierShift", "Chốt ca", "Cashier shifts", "UC71", "BR-TG-05",
     "A06", "Lễ tân chủ ca", "OPEN → CLOSED (Ca thu ngân#3)", body="CloseShiftRequest", resp="CashierShift",
     path_params=["ShiftId"], errors=(400, 401, 403, 404, 409), err_desc={409: "Ca không OPEN"},
     notes="Tổng hợp giao dịch theo phương thức.")
m.op("get", "/cashier-shifts", "listCashierShifts", "Danh sách ca", "Cashier shifts", "UC72", "BR-TG-05", "A05",
     "BRANCH_MANAGER chi nhánh", resp="CashierShift", page=True, errors=(400, 401, 403),
     query=["status=enum:OPEN,CLOSED,RECONCILED", "businessDate=date", "cashierId=int64", "page", "size"])
m.op("get", "/cashier-shifts/{shiftId}", "getCashierShift", "Chi tiết ca", "Cashier shifts", "UC71, UC72",
     "BR-TG-05", "A05, A06", "BRANCH_MANAGER chi nhánh; lễ tân chủ ca", resp="CashierShift",
     path_params=["ShiftId"], errors=(401, 403, 404))
m.op("post", "/cashier-shifts/{shiftId}/reconcile", "reconcileCashierShift", "Đối soát ca", "Cashier shifts", "UC72",
     "BR-TG-04, 05, BR-QT-15", "A05", "BRANCH_MANAGER chi nhánh", "CLOSED → RECONCILED (Ca thu ngân#6)",
     body="ReconcileShiftRequest", resp="CashierShift", path_params=["ShiftId"], errors=(400, 401, 403, 404, 409),
     err_desc={400: "`BR-TG-05` ca tự chốt chưa nhập số tiền thực đếm", 409: "Ca không CLOSED"},
     notes="Ghi chênh lệch và ghi chú (cả sai sót sau khi thu, BR-TG-04); ghi audit.")
