import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { ApiError } from './api-error';
import { clinicApi } from './clinic.api';
import { dayKey, loadDb, resetClinicDb, seedClinicDb } from './clinic-db';

// Seed (clinic-db.ts): visit-N = queue number N. visit-5 Mochi exam IN_PROGRESS (vet 5),
// visit-6 Miu exam WAITING (vet 5, appt-miu), visit-8 Kem grooming WAITING unassigned,
// order-2 = Tiêu exam PENDING 230.000 ₫ (incl. 10 × Amoxicillin).
const NOW = Date.parse('2026-10-02T09:00:00+07:00');
const VET = '5';
const OTHER_VET = 'vet-2';
const GROOMER = '6';
const DESK = '4';

const record = {
  subjective: 'Gãi nhiều vùng cổ',
  objective: { temperatureC: 38.6, weightKg: 4.2, findings: 'Da đỏ vùng cổ' },
  assessment: '',
  plan: '',
  internalNote: '',
};

/** 00-method §3.5: rule → 400 BUSINESS_RULE_VIOLATION, mã rule ở cuối message. */
const ruleViolation = (ruleId: string) => ({ errorCode: 'BUSINESS_RULE_VIOLATION', statusCode: 400, ruleId });

async function rejection(promise: Promise<unknown>): Promise<ApiError> {
  try {
    await promise;
  } catch (e) {
    if (e instanceof ApiError) return e;
    throw e;
  }
  throw new Error('expected the call to be rejected');
}

beforeEach(() => {
  vi.useFakeTimers({ toFake: ['Date'] });
  vi.setSystemTime(NOW);
  resetClinicDb(seedClinicDb(NOW));
});

afterEach(() => {
  vi.useRealTimers();
});

describe('check-in (BR-TN-01..05)', () => {
  it('turns a booked appointment into a waiting visit with an open order', async () => {
    const visit = await clinicApi.checkIn({ appointmentId: 'appt-lucky', assigneeId: VET }, DESK);

    expect(visit).toMatchObject({ status: 'WAITING', queueNo: 9, priority: 'APPOINTMENT', orderTotal: 150_000 });
    const db = loadDb(NOW);
    expect(db.appointments.find((a) => a.id === 'appt-lucky')?.status).toBe('CHECKED_IN');
    expect(db.orders.find((o) => o.id === visit.orderId)).toMatchObject({
      status: 'OPEN',
      source: 'VISIT',
      lines: [expect.objectContaining({ refId: 'svc-exam', qty: 1, autoGenerated: true })],
    });
  });

  it('refuses an appointment outside the check-in window (BR-TN-02)', async () => {
    const err = await rejection(clinicApi.checkIn({ appointmentId: 'appt-dau' }, DESK));
    expect(err).toMatchObject(ruleViolation('BR-TN-02'));
  });

  it('puts a walk-in emergency at the head of the queue', async () => {
    await clinicApi.checkIn({ petId: 'pet-mit', serviceId: 'svc-exam', emergency: true, assigneeId: VET }, DESK);

    const waiting = (await clinicApi.listTodayVisits()).filter((v) => v.status === 'WAITING');
    expect(waiting[0]).toMatchObject({ priority: 'EMERGENCY', pet: expect.objectContaining({ name: 'Mít' }) });
  });

  it('refuses to assign a groomer to an exam (BR-TN-05)', async () => {
    const err = await rejection(clinicApi.assignVisit('visit-6', GROOMER, DESK));
    expect(err).toMatchObject(ruleViolation('BR-TN-05'));
  });

  it('assigns a waiting grooming visit to a caretaker', async () => {
    const visit = await clinicApi.assignVisit('visit-8', GROOMER, DESK);
    expect(visit.assignee?.id).toBe(GROOMER);
  });
});

describe('exam room (BR-TN-05, BR-KB-01..03)', () => {
  it('lets the assigned vet call the visit', async () => {
    const visit = await clinicApi.callVisit('visit-6', VET);
    expect(visit.status).toBe('IN_PROGRESS');
    expect(visit.calledAt).toBe(new Date(NOW).toISOString());
  });

  it("refuses to call a colleague's visit (BR-TN-05)", async () => {
    const err = await rejection(clinicApi.callVisit('visit-6', OTHER_VET));
    expect(err).toMatchObject(ruleViolation('BR-TN-05'));
    expect(err.message).toMatch(/ \(BR-TN-05\)$/);
    expect(err).toMatchObject({ success: false, timestamp: expect.any(String), traceId: expect.stringMatching(/.+/) });
  });

  it('only lets the assigned vet write the record (BR-KB-01)', async () => {
    const err = await rejection(clinicApi.saveRecord('visit-5', record, OTHER_VET));
    expect(err).toMatchObject(ruleViolation('BR-KB-01'));
  });

  it('refuses a prescription above the available stock (BR-KB-03)', async () => {
    const err = await rejection(clinicApi.addVisitLine('visit-5', { kind: 'PRODUCT', refId: 'p-apoquel', qty: 999 }, VET));
    expect(err).toMatchObject(ruleViolation('BR-KB-03'));
  });

  it('refuses to complete an exam without a diagnosis (BR-KB-02)', async () => {
    const err = await rejection(clinicApi.completeVisit('visit-5', VET));
    expect(err).toMatchObject(ruleViolation('BR-KB-02'));
  });

  it('hands a diagnosed exam over to the cashier', async () => {
    await clinicApi.saveRecord('visit-5', { ...record, assessment: 'Viêm da dị ứng' }, VET);
    await clinicApi.addVisitLine('visit-5', { kind: 'PRODUCT', refId: 'p-apoquel', qty: 7 }, VET);
    await clinicApi.completeVisit('visit-5', VET);

    const pending = await clinicApi.listPendingOrders();
    expect(pending.find((o) => o.queueNo === 5)).toMatchObject({ total: 200_000 + 7 * 35_000 });
  });

  it('locks the record once the visit is completed (BR-KB-01)', async () => {
    await clinicApi.saveRecord('visit-5', { ...record, assessment: 'Viêm da dị ứng' }, VET);
    await clinicApi.completeVisit('visit-5', VET);
    const err = await rejection(clinicApi.saveRecord('visit-5', record, VET));
    expect(err.statusCode).toBe(409);
  });

  it('lets the assigned vet switch the check-in service (BR-TN-01, BR-KB-02)', async () => {
    const visit = await clinicApi.checkIn({ appointmentId: 'appt-mit', assigneeId: VET }, DESK);
    await clinicApi.callVisit(visit.id, VET);

    const detail = await clinicApi.replaceVisitService(visit.id, 'svc-exam', VET);

    expect(detail.services.map((s) => s.id)).toEqual(['svc-exam']);
    expect(detail.lines).toEqual([expect.objectContaining({ refId: 'svc-exam', unitPrice: 150_000, autoGenerated: true })]);
    expect(await rejection(clinicApi.completeVisit(visit.id, VET))).toMatchObject(ruleViolation('BR-KB-02'));
  });

  it('keeps the visit in one service group when switching (BR-TN-05)', async () => {
    const err = await rejection(clinicApi.replaceVisitService('visit-5', 'svc-groom-bath', VET));
    expect(err).toMatchObject(ruleViolation('BR-TN-05'));
  });

  it("refuses to switch the service of a colleague's visit", async () => {
    const err = await rejection(clinicApi.replaceVisitService('visit-5', 'svc-exam', OTHER_VET));
    expect(err).toMatchObject({ errorCode: 'ACCESS_DENIED_SCOPE_MISMATCH', statusCode: 403, ruleId: null });
  });

  it('lets the assignee remove the check-in line once another service is on the order (BR-TN-01)', async () => {
    const withTest = await clinicApi.addVisitLine('visit-5', { kind: 'SERVICE', refId: 'svc-blood-test', qty: 1 }, VET);
    const auto = withTest.lines.find((l) => l.autoGenerated)!;
    const after = await clinicApi.removeVisitLine('visit-5', auto.id, VET);
    expect(after.lines.map((l) => l.refId)).toEqual(['svc-blood-test']);
    expect(after.services.map((s) => s.id)).toEqual(['svc-blood-test']);
  });

  it('keeps at least one service on the visit', async () => {
    const detail = await clinicApi.getVisitDetail('visit-5');
    const auto = detail.lines.find((l) => l.autoGenerated)!;
    expect(await rejection(clinicApi.removeVisitLine('visit-5', auto.id, VET))).toMatchObject({
      errorCode: 'VALIDATION_FAILED',
      statusCode: 400,
    });
  });

  it('refuses a follow-up date on the exam day (BR-KB-06)', async () => {
    const today = new Date(NOW).toLocaleDateString('sv-SE');
    const err = await rejection(clinicApi.saveRecord('visit-5', { ...record, followUpDate: today }, VET));
    expect(err).toMatchObject(ruleViolation('BR-KB-06'));
  });

  it('refuses a follow-up date more than 180 days ahead (BR-KB-06)', async () => {
    const far = new Date(NOW + 181 * 86_400_000).toLocaleDateString('sv-SE');
    const err = await rejection(clinicApi.saveRecord('visit-5', { ...record, followUpDate: far }, VET));
    expect(err).toMatchObject(ruleViolation('BR-KB-06'));
  });
});

describe('leaving before being called (BR-TN-07)', () => {
  it('cancels the visit, its order and its appointment', async () => {
    await clinicApi.cancelVisit('visit-6', DESK);
    const db = loadDb(NOW);
    expect(db.visits.find((v) => v.id === 'visit-6')?.status).toBe('CANCELLED');
    expect(db.orders.find((o) => o.visitId === 'visit-6')?.status).toBe('CANCELLED');
    expect(db.appointments.find((a) => a.id === 'appt-miu')?.status).toBe('CANCELLED');
  });

  it('refuses once the visit was called', async () => {
    const err = await rejection(clinicApi.cancelVisit('visit-5', DESK));
    expect(err).toMatchObject({ errorCode: 'INVALID_STATE_TRANSITION', statusCode: 409 });
  });
});

describe('cashier (BR-TG-01..05, BR-SP-01)', () => {
  it('refuses to collect without an open shift (BR-TG-01)', async () => {
    const err = await rejection(
      clinicApi.collectPayment({ orderIds: ['order-2'], retailLines: [], method: 'CASH', amount: 230_000 }, DESK),
    );
    expect(err).toMatchObject(ruleViolation('BR-TG-01'));
  });

  it('opens at most one shift per receptionist (BR-TG-05)', async () => {
    await clinicApi.openShift(DESK);
    const err = await rejection(clinicApi.openShift(DESK));
    expect(err).toMatchObject(ruleViolation('BR-TG-05'));
  });

  it('collects a pending order, deducts stock and books the shift (BR-TG-04)', async () => {
    await clinicApi.openShift(DESK);
    const stockBefore = loadDb(NOW).products.find((p) => p.id === 'p-amox')!.stock;

    const receipt = await clinicApi.collectPayment(
      { orderIds: ['order-2'], retailLines: [], method: 'CASH', amount: 230_000 },
      DESK,
    );

    expect(receipt.total).toBe(230_000);
    const db = loadDb(NOW);
    expect(db.orders.find((o) => o.id === 'order-2')).toMatchObject({ status: 'PAID', paymentMethod: 'CASH' });
    expect(db.products.find((p) => p.id === 'p-amox')!.stock).toBe(stockBefore - 10);
    expect((await clinicApi.getOpenShift(DESK))?.cashTotal).toBe(230_000);
  });

  it('refuses an amount that differs from the total (BR-TG-02)', async () => {
    await clinicApi.openShift(DESK);
    const err = await rejection(
      clinicApi.collectPayment({ orderIds: ['order-2'], retailLines: [], method: 'CASH', amount: 100_000 }, DESK),
    );
    expect(err).toMatchObject(ruleViolation('BR-TG-02'));
  });

  it('sells counter items as a new paid retail order', async () => {
    await clinicApi.openShift(DESK);
    const receipt = await clinicApi.collectPayment(
      { orderIds: [], retailLines: [{ productId: 'p-pate', qty: 3 }], method: 'BANK_TRANSFER', amount: 54_000 },
      DESK,
    );

    expect(receipt.orderIds).toHaveLength(1);
    expect(loadDb(NOW).orders.find((o) => o.id === receipt.orderIds[0])).toMatchObject({
      source: 'RETAIL',
      status: 'PAID',
      paymentMethod: 'BANK_TRANSFER',
    });
  });

  it('refuses prescription drugs over the counter (BR-SP-01)', async () => {
    await clinicApi.openShift(DESK);
    const err = await rejection(
      clinicApi.collectPayment(
        { orderIds: [], retailLines: [{ productId: 'p-amox', qty: 1 }], method: 'CASH', amount: 8_000 },
        DESK,
      ),
    );
    expect(err).toMatchObject(ruleViolation('BR-SP-01'));
  });

  it("refuses to combine two customers' orders (BR-TG-03)", async () => {
    await clinicApi.openShift(DESK);
    const err = await rejection(
      clinicApi.collectPayment({ orderIds: ['order-2', 'order-3'], retailLines: [], method: 'CASH', amount: 410_000 }, DESK),
    );
    expect(err).toMatchObject(ruleViolation('BR-TG-03'));
  });
});

describe('stock shared by counter and exam room (BR-BH-04)', () => {
  it('keeps stock held by a prescription out of counter sales', async () => {
    await clinicApi.addVisitLine('visit-5', { kind: 'PRODUCT', refId: 'p-vitamin', qty: 15 }, VET);
    await clinicApi.openShift(DESK);
    const err = await rejection(
      clinicApi.collectPayment({ orderIds: [], retailLines: [{ productId: 'p-vitamin', qty: 10 }], method: 'CASH', amount: 2_800_000 }, DESK),
    );
    expect(err).toMatchObject(ruleViolation('BR-BH-04'));
  });

  it('shows counter availability net of held stock', async () => {
    await clinicApi.addVisitLine('visit-5', { kind: 'PRODUCT', refId: 'p-vitamin', qty: 15 }, VET);
    const catalog = await clinicApi.getCatalog();
    expect(catalog.products.find((p) => p.id === 'p-vitamin')?.available).toBe(5);
  });
});

describe('reads', () => {
  it('lists only appointments inside the check-in window (BR-TN-02)', async () => {
    const arrivals = await clinicApi.listArrivals();
    expect(arrivals.map((a) => a.appointmentId).sort()).toEqual(['appt-lucky', 'appt-mit']);
  });

  it("summarises today's work for the dashboard", async () => {
    expect(await clinicApi.getDashboardSummary()).toMatchObject({
      visitsToday: 8,
      waiting: 3,
      inProgress: 2,
      pendingPayment: 2,
      revenueToday: 80_000,
    });
  });

  it("shows a pet's earlier visits, newest first", async () => {
    const detail = await clinicApi.getVisitDetail('visit-5');
    expect(detail.history.map((h) => h.assessment)).toEqual(['', 'Viêm tai ngoài']);
  });

  it('finds customers by name typed without diacritics', async () => {
    const found = await clinicApi.searchCustomers('nguyen thu');
    expect(found.map((c) => c.name)).toEqual(['Nguyễn Thu Trang']);
  });

  it('finds the owner from a pet name', async () => {
    const found = await clinicApi.searchCustomers('dau');
    expect(found.map((c) => c.name)).toEqual(['Trịnh Gia Bảo']);
  });

  it('finds customers by phone digits', async () => {
    const found = await clinicApi.searchCustomers('0912554');
    expect(found.map((c) => c.name)).toEqual(['Trần Đức Huy']);
  });
});

describe('storage', () => {
  it('starts a fresh day when the stored clinic is from yesterday', () => {
    resetClinicDb(seedClinicDb(NOW - 86_400_000));
    expect(loadDb(NOW).day).toBe(dayKey(NOW));
  });

  it("gives a new day's visits ids never used the day before", async () => {
    const yesterday = await clinicApi.checkIn({ petId: 'pet-dau', serviceId: 'svc-exam', assigneeId: VET }, DESK);
    vi.setSystemTime(NOW + 86_400_000);
    resetClinicDb(seedClinicDb(NOW + 86_400_000));
    const today = await clinicApi.checkIn({ petId: 'pet-dau', serviceId: 'svc-exam', assigneeId: VET }, DESK);
    expect(today.id).not.toBe(yesterday.id);
  });

  it("keeps today's changes across reloads", async () => {
    await clinicApi.callVisit('visit-6', VET);
    expect(loadDb(NOW).visits.find((v) => v.id === 'visit-6')?.status).toBe('IN_PROGRESS');
  });
});
