// Clinic domain types for the staff workspaces.
// Status unions mirror docs v13 (docs/03-state-machines.md) — never add a value that isn't there.

export type VisitStatus = 'WAITING' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
export type AppointmentStatus = 'BOOKED' | 'CHECKED_IN' | 'COMPLETED' | 'CANCELLED' | 'NO_SHOW';
export type OrderStatus = 'OPEN' | 'PENDING' | 'PAID' | 'CANCELLED';
export type OrderSource = 'VISIT' | 'RETAIL' | 'BOARDING';
export type ShiftStatus = 'OPEN' | 'CLOSED' | 'RECONCILED';
/** BR-TG-02: tiền mặt + chuyển khoản (lễ tân xác nhận thủ công). */
export type PaymentMethod = 'CASH' | 'BANK_TRANSFER';

/** Nhóm Khám/Tiêm mang loại KHÁM | TIÊM (BR-SP-06); Thẩm mỹ = grooming. */
export type ServiceKind = 'EXAM' | 'VACCINATION' | 'GROOMING';
export type StaffPosition = 'VET' | 'CARETAKER' | 'RECEPTIONIST' | 'BRANCH_MANAGER';
export type Species = 'DOG' | 'CAT';
export type ProductCategory = 'FOOD' | 'MEDICINE' | 'ACCESSORY' | 'HYGIENE';
/** BR-TN-04 bands, decided at check-in (BR-TN-03 demotes late appointments). */
export type QueuePriority = 'EMERGENCY' | 'APPOINTMENT' | 'WALK_IN';

export interface Customer {
  id: string;
  name: string;
  phone: string;
}

export interface Pet {
  id: string;
  customerId: string;
  name: string;
  species: Species;
  breed: string;
  birthYear?: number;
  weightKg?: number;
  /** Staff-facing handling alert, e.g. "Cắn khi cắt móng". */
  alert?: string;
}

export interface Staff {
  id: string;
  name: string;
  position: StaffPosition;
}

export interface Service {
  id: string;
  name: string;
  kind: ServiceKind;
  price: number;
  durationMin: number;
}

export interface Product {
  id: string;
  name: string;
  category: ProductCategory;
  price: number;
  stock: number;
  unit: string;
  /** BR-SP-01: not sold at the counter, only via a VET prescription. */
  prescriptionOnly: boolean;
  /** Set for vaccines — recording one counts as an injection (BR-KB-02). */
  vaccineType?: string;
}

export interface Appointment {
  id: string;
  customerId: string;
  petId: string;
  serviceId: string;
  startsAt: string;
  status: AppointmentStatus;
}

/** SOAP view of the medical record. Locked once the visit completes (BR-KB-01). */
export interface MedicalRecord {
  subjective: string;
  objective: {
    temperatureC?: number;
    weightKg?: number;
    heartRate?: number;
    findings: string;
  };
  /** Chẩn đoán — required before completing an EXAM visit (BR-KB-02). */
  assessment: string;
  plan: string;
  /** Staff only, hidden from customers (BR-KB-01). */
  internalNote: string;
  /** Ngày tái khám (BR-KB-06), yyyy-mm-dd. */
  followUpDate?: string;
  updatedAt?: string;
}

export interface Visit {
  id: string;
  queueNo: number;
  petId: string;
  customerId: string;
  appointmentId?: string;
  serviceIds: string[];
  emergency: boolean;
  priority: QueuePriority;
  scheduledAt?: string;
  assigneeId?: string;
  status: VisitStatus;
  checkedInAt: string;
  calledAt?: string;
  completedAt?: string;
  orderId: string;
  record?: MedicalRecord;
}

export interface OrderLine {
  id: string;
  kind: 'SERVICE' | 'PRODUCT';
  refId: string;
  name: string;
  unitPrice: number;
  qty: number;
  addedBy: string;
  /** The service line created at check-in (BR-TN-01). */
  autoGenerated: boolean;
  vaccine?: boolean;
}

export interface Order {
  id: string;
  source: OrderSource;
  customerId: string;
  visitId?: string;
  status: OrderStatus;
  lines: OrderLine[];
  createdAt: string;
  paidAt?: string;
  paymentMethod?: PaymentMethod;
  shiftId?: string;
}

export interface CashierShift {
  id: string;
  receptionistId: string;
  status: ShiftStatus;
  openedAt: string;
  cashTotal: number;
  transferTotal: number;
}

export type ActivityKind = 'CHECK_IN' | 'ASSIGN' | 'CALL' | 'COMPLETE' | 'CANCEL' | 'PAY' | 'SHIFT';

export interface ActivityEntry {
  id: string;
  at: string;
  kind: ActivityKind;
  text: string;
}

// ---------- Response shapes (what each workspace reads) ----------

export interface VisitView {
  id: string;
  queueNo: number;
  status: VisitStatus;
  priority: QueuePriority;
  emergency: boolean;
  pet: Pick<Pet, 'id' | 'name' | 'species' | 'breed' | 'alert'>;
  customer: Customer;
  services: Pick<Service, 'id' | 'name' | 'kind'>[];
  assignee?: Pick<Staff, 'id' | 'name'>;
  scheduledAt?: string;
  checkedInAt: string;
  calledAt?: string;
  completedAt?: string;
  orderId: string;
  orderStatus: OrderStatus;
  orderTotal: number;
}

export interface PetHistoryEntry {
  visitId: string;
  date: string;
  services: string[];
  assessment?: string;
  followUpDate?: string;
}

export interface VisitDetail extends VisitView {
  petProfile: Pet;
  record: MedicalRecord | null;
  lines: OrderLine[];
  history: PetHistoryEntry[];
}

export interface ArrivalView {
  appointmentId: string;
  startsAt: string;
  pet: Pick<Pet, 'id' | 'name' | 'species' | 'breed'>;
  customer: Customer;
  service: Pick<Service, 'id' | 'name' | 'kind'>;
}

export interface PendingOrderView {
  id: string;
  source: OrderSource;
  customer: Customer;
  queueNo?: number;
  petName?: string;
  lines: OrderLine[];
  total: number;
  createdAt: string;
}

export interface CustomerWithPets extends Customer {
  pets: Pet[];
}

/** `available` = on hand minus what open/pending orders hold (tồn khả dụng, BR-BH-04). */
export interface CatalogProduct extends Product {
  available: number;
}

export interface Catalog {
  services: Service[];
  products: CatalogProduct[];
}

export interface DashboardSummary {
  visitsToday: number;
  waiting: number;
  inProgress: number;
  pendingPayment: number;
  revenueToday: number;
  byKind: Record<ServiceKind, number>;
  activity: ActivityEntry[];
}
